### ISSUE TITLE
npm3+ error

### ISSUE THREAD

**Issue by rondonjon** [webpack/jshint-loader#18]
I am getting the following warning from npm 2.14.1 when installing jshint-loader as a dependency:

```
npm WARN peerDependencies The peer dependency jshint@^2.5.0 included from jshint-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by Vestride** [comment]
I also get this message right after the peerDependencies message with npm 2.14.3

```
npm WARN prefer global jshint@2.8.0 should be installed with -g
```

**Comment by kostasmanionis** [comment]
Old issue, closing.

If anybody is interested - this mean you're going to have explicitly install `jshint-loader` when moving to npm3 or newer. npm will no longer do this for you.

The second message is because jshint prefers to be installed globally. Not really related to `jshint-loader`. It's just a warning, safe to ignore it.
